FROM php:5.6.23-fpm

RUN apt-get update && apt-get install -y libmcrypt-dev
RUN docker-php-ext-install mbstring pdo_mysql tokenizer

COPY php-fpm/php.ini /usr/local/etc/php/

WORKDIR /var/www/
COPY ../site ./site

RUN usermod -u 1000 www-data

CMD ["/php-fpm"]